//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_DeviceBorrowingSystemEntities1 : DbContext
    {
        public db_DeviceBorrowingSystemEntities1()
            : base("name=db_DeviceBorrowingSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Calibration> tbl_Calibration { get; set; }
        public DbSet<tbl_chamber_content> tbl_chamber_content { get; set; }
        public DbSet<tbl_chamber_detail> tbl_chamber_detail { get; set; }
        public DbSet<tbl_device_detail> tbl_device_detail { get; set; }
        public DbSet<tbl_equipment_detail> tbl_equipment_detail { get; set; }
        public DbSet<tbl_FloatingPrice> tbl_FloatingPrice { get; set; }
        public DbSet<tbl_Project> tbl_Project { get; set; }
        public DbSet<tbl_ProxyUser> tbl_ProxyUser { get; set; }
        public DbSet<tbl_summary_dev_title> tbl_summary_dev_title { get; set; }
        public DbSet<tbl_TestCategory> tbl_TestCategory { get; set; }
        public DbSet<tbl_DeviceBooking> tbl_DeviceBooking { get; set; }
        public DbSet<tbl_project_stage> tbl_project_stage { get; set; }
        public DbSet<tbl_captcha> tbl_captcha { get; set; }
        public DbSet<tbl_Person> tbl_Person { get; set; }
        public DbSet<tbl_new_person> tbl_new_person { get; set; }
    }
}
