//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Project
    {
        public string PJ_Code { get; set; }
        public string PJ_Name { get; set; }
        public string Cust_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
