//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project_stage
    {
        public int ps_id { get; set; }
        public string ps_pj_id { get; set; }
        public string ps_stage { get; set; }
        public Nullable<System.DateTime> ps_from { get; set; }
        public Nullable<System.DateTime> ps_to { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
