//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_new_person
    {
        public string P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Password { get; set; }
        public string P_Department { get; set; }
        public string P_ChargeDepartment { get; set; }
        public string P_Email { get; set; }
        public string P_ExNumber { get; set; }
        public int P_Role { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public string P_Location { get; set; }
        public bool P_RegisterStatus { get; set; }
        public bool P_Activate { get; set; }
    }
}
