//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceBooking
    {
        public string Booking_ID { get; set; }
        public string Loaner_ID { get; set; }
        public string Device_ID { get; set; }
        public string Project_ID { get; set; }
        public string TestCategory_ID { get; set; }
        public string PJ_Stage { get; set; }
        public Nullable<System.DateTime> Loan_DateTime { get; set; }
        public Nullable<System.DateTime> Plan_To_ReDateTime { get; set; }
        public Nullable<System.DateTime> Real_ReDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public string Reviewer_ID { get; set; }
        public Nullable<System.DateTime> Warn_Date { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Review_Comment { get; set; }
        public bool db_is_recurrence { get; set; }
        public string db_recurrence { get; set; }
        public Nullable<System.TimeSpan> db_start { get; set; }
        public Nullable<System.TimeSpan> db_end { get; set; }
    }
}
