//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_device_detail
    {
        public int id { get; set; }
        public string d_id { get; set; }
        public string d_customid { get; set; }
        public string d_class { get; set; }
        public string d_interface { get; set; }
        public Nullable<int> d_status { get; set; }
        public Nullable<System.DateTime> d_date { get; set; }
    }
}
