//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FloatingPrice
    {
        public int id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Device_ID { get; set; }
        public Nullable<double> Inside_cost { get; set; }
        public Nullable<double> Outside_cost { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
